- README.md
It was unclear how to import the projects. I think "Maven" is the way to go, isn't it?
> Refine instructions at README.md

- org.opentosca.bus.management.api.osgievent/src/org/opentosca/bus/management/api/osgievent/MBEventHandler.java
After a plan invocation by the `MBEventHandler` class, a polling Camel consumer is started in order to wait for a response. Using `consumer.start()` the current thread will block until the response will be received. Furthermore, due to the fact that the `MBEventHandler` is a singleton, only one plan can run at one point in time.
In order to decouple this, we can use Java's Executor service in order to handle the reception of responses in a separate thread (aka. callable).
> [PlanInvocation] Receiving plan responses using Java's executor service

- org.opentosca.container.api.legacy/src/org/opentosca/container/api/legacy/resources/csar/servicetemplate/relationshiptemplate/instances/RelationshipTemplateInstancePropertiesResource.java
- org.opentosca.container.core.impl/src/org/opentosca/container/core/impl/persistence/Converters.java
- org.opentosca.container.core.impl/src/org/opentosca/container/core/impl/persistence/RelationInstanceDAO.java
- org.opentosca.container.core.impl/src/org/opentosca/container/core/impl/service/InstanceDataServiceImpl.java
- org.opentosca.container.core/src/org/opentosca/container/core/model/instance/NodeInstance.java
- org.opentosca.container.core/src/org/opentosca/container/core/model/instance/RelationInstance.java
- org.opentosca.container.core/src/org/opentosca/container/core/next/model/NodeTemplateInstance.java
- org.opentosca.container.core/src/org/opentosca/container/core/next/model/RelationshipTemplateInstance.java
- org.opentosca.container.core/src/org/opentosca/container/core/next/repository/RelationshipTemplateInstanceRepository.java
- org.opentosca.planbuilder.importer/META-INF/MANIFEST.MF
- org.opentosca.planbuilder.importer/src/org/opentosca/planbuilder/importer/context/impl/ArtifactTemplateImpl.java
- org.opentosca.planbuilder.importer/src/org/opentosca/planbuilder/importer/context/impl/ArtifactTypeImpl.java
- org.opentosca.planbuilder.importer/src/org/opentosca/planbuilder/importer/context/impl/DefinitionsImpl.java
- org.opentosca.planbuilder.model/src/org/opentosca/planbuilder/model/tosca/AbstractArtifactTemplate.java
- org.opentosca.planbuilder.model/src/org/opentosca/planbuilder/model/tosca/AbstractArtifactType.java
- org.opentosca.planbuilder.model/src/org/opentosca/planbuilder/model/tosca/AbstractDefinitions.java
- org.opentosca.planbuilder.prephase.plugin.scriptiaonlinux/src/org/opentosca/planbuilder/prephase/plugin/scriptiaonlinux/PrePhasePlugin.java
- org.opentosca.planbuilder/src/org/opentosca/planbuilder/utils/Utils.java
**Fixes**:
* Plan Builder: Check hierarchy of artifact types
* Relationship Instance API: Fixes due to move to new JPA layer
> Plan Builder and Relationship Instance API enhancements

- docs/ApplicationBus.md
Translated to english with some minor markdown changes.
> ApplicationBus.md enhancement

- org.opentosca.bus.management.plugins.remote.service.impl/META-INF/artifacttypes/Script.xml
- org.opentosca.bus.management.plugins.remote.service.impl/src/org/opentosca/bus/management/plugins/remote/service/impl/ManagementBusPluginRemoteServiceImpl.java
> Fix ia invocation

- org.opentosca.planbuilder.model/src/org/opentosca/planbuilder/model/utils/ModelUtils.java
Fixes an issue where finding infrastructure edges was not correct
* looks for infrastructure edges from the starting node as well instead of looking only on infrastructure nodes
> fixes issue with missing infrastructure edges in scale-out plan generation

- org.opentosca.container.api/src/org/opentosca/container/api/controller/BoundaryDefinitionController.java
- org.opentosca.container.api/src/org/opentosca/container/api/controller/NodeTemplateController.java
- org.opentosca.container.api/src/org/opentosca/container/api/dto/NodeOperationDTO.java
- org.opentosca.container.api/src/org/opentosca/container/api/dto/NodeTemplateDTO.java
- org.opentosca.container.api/src/org/opentosca/container/api/dto/boundarydefinitions/OperationDTO.java
- org.opentosca.container.api/src/org/opentosca/container/api/service/NodeTemplateService.java
- org.opentosca.container.core/src/org/opentosca/container/core/engine/IToscaEngineService.java
- org.opentosca.container.core/src/org/opentosca/container/core/engine/impl/ToscaEngineServiceImpl.java
Adds additional info for node templates inside the API to get the implemented interfaces
> adds feature to get node interfaces with the container api

- org.opentosca.bus.management.service.impl/src/org/opentosca/bus/management/service/impl/ManagementBusServiceImpl.java
- org.opentosca.bus.management/src/org/opentosca/bus/management/utils/MBUtils.java
- org.opentosca.planbuilder.model/src/org/opentosca/planbuilder/model/utils/ModelUtils.java
Management Bus searches the topology to find properties matching open parameters.
> Advanced parameter resolving

- org.opentosca.bus.management.invocation.plugin.script/src/org/opentosca/bus/management/invocation/plugin/script/ManagementBusInvocationPluginScript.java
Adds additional logic to escape special characters in bash environment variables such as tabs and spaces
> adds more escaping to script handling plugin to enable better handling of e.g. python scripts as environment variables

- org.opentosca.container.api/OSGI-INF/InstanceService.xml
- org.opentosca.container.api/src/org/opentosca/container/api/controller/ServiceTemplateInstanceController.java
- org.opentosca.container.api/src/org/opentosca/container/api/service/InstanceService.java
- org.opentosca.container.api/src/org/opentosca/container/api/service/PropertyMappingsHelper.java
Adds the ability to evaluate property mappings in service template instances
* port the relevant functionality from the core.impl.InstanceDataService to api.service.InstanceService
**Fixes**: 
* https://github.com/OpenTOSCA/container-client/issues/13
> Add ability to evaluate property mappings

- org.opentosca.bus.management.api.soaphttp/META-INF/wsdl/invoker.xsd
- org.opentosca.bus.management.api.soaphttp/src/org/opentosca/bus/management/api/soaphttp/model/InvokeOperationAsync.java
- org.opentosca.bus.management.api.soaphttp/src/org/opentosca/bus/management/api/soaphttp/model/InvokeOperationSync.java
- org.opentosca.bus.management.api.soaphttp/src/org/opentosca/bus/management/api/soaphttp/processor/RequestProcessor.java
- org.opentosca.bus.management.service.impl/src/org/opentosca/bus/management/service/impl/ManagementBusServiceImpl.java
- org.opentosca.container.api/src/org/opentosca/container/api/dto/plan/PlanInstanceEventDTO.java
- org.opentosca.container.core/src/org/opentosca/container/core/next/model/PlanInstanceEvent.java
- org.opentosca.planbuilder.provphase.plugin.invoker/META-INF/resources/assignInvokerAsyncMessage.xml
- org.opentosca.planbuilder.provphase.plugin.invoker/META-INF/resources/correlationIdCopy.xml
- org.opentosca.planbuilder.provphase.plugin.invoker/src/org/opentosca/planbuilder/provphase/plugin/invoker/bpel/handlers/ResourceHandler.java
Adds more logs for the execution times of IA and Plan executions
> Log IA and plan execution times

- org.opentosca.bus.application.api.jsonhttp/src/org/opentosca/bus/application/api/jsonhttp/Activator.java
- org.opentosca.bus.application.api.resthttp/src/org/opentosca/bus/application/api/resthttp/Activator.java
- org.opentosca.bus.application.api.soaphttp/src/org/opentosca/bus/application/api/soaphttp/Activator.java
- org.opentosca.bus.application.plugin.jsonhttp.service.impl/src/org/opentosca/bus/application/plugin/jsonhttp/service/impl/Activator.java
- org.opentosca.bus.application.service.impl/src/org/opentosca/bus/application/service/impl/Activator.java
- org.opentosca.bus.management.api.osgievent/src/org/opentosca/bus/management/api/osgievent/Activator.java
- org.opentosca.bus.management.api.resthttp/src/org/opentosca/bus/management/api/resthttp/Activator.java
- org.opentosca.bus.management.api.soaphttp/src/org/opentosca/bus/management/api/soaphttp/Activator.java
- org.opentosca.planbuilder.core.bpel/src/org/opentosca/planbuilder/core/bpel/tosca/handlers/PropertyVariableHandler.java
- org.opentosca.planbuilder.model/src/org/opentosca/planbuilder/model/utils/ModelUtils.java
- org.opentosca.planbuilder.postphase.plugin.monitoring/src/org/opentosca/planbuilder/postphase/plugin/monitoring/bpel/impl/BPELMonitoringPlugin.java
- org.opentosca.planbuilder.type.plugin.dockercontainer/src/org/opentosca/planbuilder/type/plugin/dockercontainer/bpel/handler/BPELDockerContainerTypePluginHandler.java
- org.opentosca.planbuilder.type.plugin.ubuntuvm/src/org/opentosca/planbuilder/type/plugin/ubuntuvm/bpel/BPELUbuntuVmTypePluginHandler.java
- org.opentosca.planbuilder/src/org/opentosca/planbuilder/plugins/registry/PluginRegistry.java
Adds multiple small fixes and enhancements
> minor fixes

- org.opentosca.planbuilder.core.bpel/src/org/opentosca/planbuilder/core/bpel/handlers/BPELFinalizer.java
- org.opentosca.planbuilder.core.bpel/src/org/opentosca/planbuilder/core/bpel/handlers/BPELPlanHandler.java
- org.opentosca.planbuilder.core.bpel/src/org/opentosca/planbuilder/core/bpel/tosca/handlers/SimplePlanBuilderServiceInstanceHandler.java
- org.opentosca.planbuilder.core.bpel/src/org/opentosca/planbuilder/core/bpel/typebasedplanbuilder/BPELBackupManagementProcessBuilder.java
- org.opentosca.planbuilder.core.bpel/src/org/opentosca/planbuilder/core/bpel/typebasedplanbuilder/BPELBuildProcessBuilder.java
- org.opentosca.planbuilder.core.bpel/src/org/opentosca/planbuilder/core/bpel/typebasedplanbuilder/BPELDefrostProcessBuilder.java
- org.opentosca.planbuilder.core.bpel/src/org/opentosca/planbuilder/core/bpel/typebasedplanbuilder/BPELFreezeProcessBuilder.java
- org.opentosca.planbuilder.core.bpel/src/org/opentosca/planbuilder/core/bpel/typebasedplanbuilder/BPELScaleOutProcessBuilder.java
- org.opentosca.planbuilder.core.bpel/src/org/opentosca/planbuilder/core/bpel/typebasedplanbuilder/BPELTerminationProcessBuilder.java
- org.opentosca.planbuilder.core.bpel/src/org/opentosca/planbuilder/core/bpel/typebasedplanbuilder/BPELTestManagementProcessBuilder.java
- org.opentosca.planbuilder.core.bpel/src/org/opentosca/planbuilder/core/bpel/typebasedplanbuilder/BPELTransformationProcessBuilder.java
- org.opentosca.planbuilder.model/src/org/opentosca/planbuilder/model/plan/AbstractActivity.java
- org.opentosca.planbuilder.model/src/org/opentosca/planbuilder/model/plan/bpel/BPELPlan.java
- org.opentosca.planbuilder.model/src/org/opentosca/planbuilder/model/plan/bpel/BPELScope.java
- org.opentosca.planbuilder.postphase.plugin.instancedata/src/org/opentosca/planbuilder/postphase/plugin/instancedata/bpel/Handler.java
- org.opentosca.planbuilder/src/org/opentosca/planbuilder/AbstractTransformingPlanbuilder.java
+ FIxes issue with identical Id's between two Service Templates in Transformation Plan Builder
+ Adds setting proper states when plans fail
> Small fixes for Plans

- org.opentosca.container.api/src/org/opentosca/container/api/controller/SituationsController.java
- org.opentosca.container.api/src/org/opentosca/container/api/dto/situations/SituationDTO.java
- org.opentosca.container.api/src/org/opentosca/container/api/dto/situations/SituationTriggerDTO.java
- org.opentosca.container.api/src/org/opentosca/container/api/service/InstanceService.java
- org.opentosca.container.core/src/org/opentosca/container/core/next/model/Situation.java
- org.opentosca.container.core/src/org/opentosca/container/core/next/model/SituationTrigger.java
Add eventProbability and evenTime parameters for eventual proactive situation triggering
- Added two variables: `float eventProbability`, `String eventTime`
- Added getters + setters
- Added two variables: `float eventProbability`, `String eventTime`
- Added getters + setters
- Chnaged `converter` method to handle new variabes
- Changed **POST Response** for "/triggers", `createSituationTrigger` method, to accept both new variables
- Changed `createNewSituationTrigger` method to accept both new parameters as input and handles them correctly
The default value of variable `eventProbability` is set to `-1.0f` since 0.0 is a possible real value it coudl take. It is only assinged if it is **not** `-1.0f`
The defautl value of variable `eventTime` is set to `null
`
> MasterThesis: Proactive Situation Triggering

- org.opentosca.container.api/OSGI-INF/SituationsController.xml
- org.opentosca.container.api/src/org/opentosca/container/api/controller/SituationsController.java
- org.opentosca.container.api/src/org/opentosca/container/api/dto/situations/SituationTriggerDTO.java
- org.opentosca.container.api/src/org/opentosca/container/api/service/InstanceService.java
- org.opentosca.container.core/src/org/opentosca/container/core/next/model/SituationTrigger.java
- org.opentosca.container.core/src/org/opentosca/container/core/next/trigger/SituationTriggerInstanceListener.java
If a Situation Trigger should have invoked a Build Plan it threw nullpointers as it couldn't find a service instance
> fixes situation triggers to work with build plans

- org.opentosca.container.core.tosca/src/org/opentosca/container/core/tosca/convention/Utils.java
- org.opentosca.planbuilder.prephase.plugin.fileupload/src/org/opentosca/planbuilder/prephase/plugin/fileupload/bpel/BPELPrePhasePlugin.java
- org.opentosca.planbuilder.type.plugin.connectsto/src/org/opentosca/planbuilder/type/plugin/connectsto/bpel/handler/BPELConnectsToPluginHandler.java
To support Docker Containers as underlying infrastructure, the connectsTo operation must be executed which was suppressed by a wrong check for supported deployment pairs.
**Fixes**: 
* recusively check isSupportedDeployment pair
* some typos
> Fix Docker Containers connecting to each other

- org.opentosca.container.core.tosca/src/org/opentosca/container/core/tosca/convention/Types.java
- org.opentosca.container.core.tosca/src/org/opentosca/container/core/tosca/convention/Utils.java
- org.opentosca.planbuilder.type.plugin.ubuntuvm/src/org/opentosca/planbuilder/type/plugin/ubuntuvm/bpel/BPELUbuntuVmTypePlugin.java
- org.opentosca.planbuilder.type.plugin.ubuntuvm/src/org/opentosca/planbuilder/type/plugin/ubuntuvm/bpel/BPELUbuntuVmTypePluginHandler.java
* Adds new OpenStack NodeType as supported Infrastructure
> Add OpenStack Train Support

- org.opentosca.container.api/src/org/opentosca/container/api/service/InstanceService.java
- org.opentosca.container.core/src/org/opentosca/container/core/next/model/SituationTriggerProperty.java
fixes #132 by saving the inputs properly and changing the jpa annotations
> fixes issue with situation trigger inputs not beeing stored and retrieved properly

- README.md
Just some info how to setup the code in eclipse
> updates README with info how to setup code in Eclipse

- org.opentosca.container.control/src/main/java/org/opentosca/container/control/impl/OpenToscaControlServiceImpl.java
- org.opentosca.container.engine.plan.plugin.bpel/src/main/java/org/opentosca/container/engine/plan/plugin/bpel/BpelPlanEnginePlugin.java
- org.opentosca.container.engine.plan.plugin.camunda/src/main/java/org/opentosca/container/engine/plan/plugin/camunda/CamundaPlanEnginePlugin.java
- org.opentosca.container.engine.plan/src/main/java/org/opentosca/container/engine/plan/impl/PlanEngineImpl.java
Fixes retrieving of BPMN plans within CSAR based on the winery backend
Match namespace handling to winery
> fixes handling of bpmn plan deployment with the new winery backend

- org.opentosca.container.core/src/main/java/org/opentosca/container/core/plan/ChoreographyHandler.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.postphase.plugin.instancedata/src/main/java/org/opentosca/planbuilder/postphase/plugin/instancedata/bpel/Handler.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.provphase.plugin.invoker/src/main/java/org/opentosca/planbuilder/provphase/plugin/invoker/bpel/handlers/BPELNotifyHandler.java
- moves some tag names into constants for handling choreographies
- updates some tag names for handling choreographies
Changes code to reflect latest changes of topologies which are modeled to be deployed within a choreography
> Update choreography handling

- .github/workflows/maven.yml
- README.md
- org.opentosca.bus/org.opentosca.bus.management.api.soaphttp/src/main/java/org/opentosca/bus/management/api/soaphttp/model/ReceiveNotifyPartners.java
- org.opentosca.container.core/src/main/java/org/opentosca/container/core/model/choreography/SituationRule.java
- pom.xml
As we only needed lombok for really small things, the balance between use and setup within IDE was not right. Removes lombok as it does not provide real value
> removes lombok from project

- .github/workflows/maven.yml
- org.opentosca.container.war/src/test/java/MyTinyToDoIntegrationTest.java
Instead of cloning the public repo inside the junit test it is better to clone via github actions, and maybe reducing traffic
> configure github actions to clone TOSCA public repo

- .github/workflows/maven.yml
- org.opentosca.container.war/src/test/java/MyTinyToDoIntegrationTest.java
Changes test repository to our internal TOSCA repository, enabling to test against the latest versions of csars
> changes test repository from public to internal

- org.opentosca.bus/org.opentosca.bus.management.api.soaphttp/src/main/java/org/opentosca/bus/management/api/soaphttp/processor/RequestProcessor.java
fixes a bug in the management bus, where it is assumed that every ubuntu node has a DA...
> check for DAs

- org.opentosca.bus/org.opentosca.bus.management.service/src/main/java/org/opentosca/bus/management/service/impl/util/Util.java
> fix handling of properties of artifactTemplates

- .github/workflows/maven.yml
- org.opentosca.container.api/src/main/java/org/opentosca/container/api/service/CsarService.java
- org.opentosca.container.api/src/main/java/org/opentosca/container/api/service/InstanceService.java
- org.opentosca.container.api/src/main/java/org/opentosca/container/api/service/PlanService.java
- org.opentosca.container.core/src/main/java/org/opentosca/container/core/common/Settings.java
- org.opentosca.container.core/src/main/java/org/opentosca/container/core/next/model/ServiceTemplateInstanceState.java
- org.opentosca.container.core/src/main/resources/application.properties
- org.opentosca.container.war/src/test/java/org/opentosca/container/war/tests/AdaptMultiMyTinyToDoIntegrationTest.java
- org.opentosca.container.war/src/test/java/org/opentosca/container/war/tests/MigrateMyTinyToDo2MultiMyTinyToDoIntegrationTest.java
- org.opentosca.container.war/src/test/java/org/opentosca/container/war/tests/MultiMyTinyToDoIntegrationTest.java
- org.opentosca.container.war/src/test/java/org/opentosca/container/war/tests/MyTinyToDoIntegrationTest.java
- org.opentosca.container.war/src/test/java/org/opentosca/container/war/tests/TestUtils.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.core.bpel/src/main/java/org/opentosca/planbuilder/core/bpel/typebasedplanbuilder/BPELScaleOutProcessBuilder.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.core.bpel/src/main/java/org/opentosca/planbuilder/core/bpel/typebasedplanbuilder/BPELTransformationProcessBuilder.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.core/src/main/java/org/opentosca/planbuilder/core/AbstractScaleOutPlanBuilder.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.core/src/main/java/org/opentosca/planbuilder/core/AbstractTransformingPlanbuilder.java
- test.properties
Adds some fixes within the transformation plan builder and multiple tests for the plan generators
> Fix and test transformation plan generation

- org.opentosca.planbuilder/org.opentosca.planbuilder.core.bpel/src/main/java/org/opentosca/planbuilder/core/bpel/handlers/BPELPlanHandler.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.core.bpel/src/main/java/org/opentosca/planbuilder/core/bpel/typebasednodehandler/BPELPluginHandler.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.core.bpel/src/main/java/org/opentosca/planbuilder/core/bpel/typebasedplanbuilder/BPELBackupManagementProcessBuilder.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.core.bpel/src/main/java/org/opentosca/planbuilder/core/bpel/typebasedplanbuilder/BPELBuildProcessBuilder.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.core.bpel/src/main/java/org/opentosca/planbuilder/core/bpel/typebasedplanbuilder/BPELDefrostProcessBuilder.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.core.bpel/src/main/java/org/opentosca/planbuilder/core/bpel/typebasedplanbuilder/BPELFreezeProcessBuilder.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.core.bpel/src/main/java/org/opentosca/planbuilder/core/bpel/typebasedplanbuilder/BPELPolicyAwareBuildProcessBuilder.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.core.bpel/src/main/java/org/opentosca/planbuilder/core/bpel/typebasedplanbuilder/BPELScaleOutProcessBuilder.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.core.bpel/src/main/java/org/opentosca/planbuilder/core/bpel/typebasedplanbuilder/BPELSituationAwareBuildProcessBuilder.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.core.bpel/src/main/java/org/opentosca/planbuilder/core/bpel/typebasedplanbuilder/BPELTerminationProcessBuilder.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.core.bpel/src/main/java/org/opentosca/planbuilder/core/bpel/typebasedplanbuilder/BPELTestManagementProcessBuilder.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.core.bpel/src/main/java/org/opentosca/planbuilder/core/bpel/typebasedplanbuilder/BPELUpdateProcessBuilder.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.model/src/main/java/org/opentosca/planbuilder/model/utils/ModelUtils.java
refactors some logging information within the plan builder to make the log a little less verbose when not debugging
> refactors some logging information within the plan builder

- .github/workflows/dockerhub.yml
Add Github Action to build Containter image for Dockerhub
> Add Github action to push Docker image to Dockerhub

- org.opentosca.container.core/src/main/java/org/opentosca/container/core/engine/ToscaEngine.java
Fix issue with using the NodeTypImplementation of the wrong NodeType if there are multiple in the type hierarchie implementing the same operation
> Keep NodeTypeImpls in hierarchy order to avoid using wrong impl

- org.opentosca.planbuilder/org.opentosca.planbuilder.core.bpel/src/main/java/org/opentosca/planbuilder/core/bpel/context/BPELPlanContext.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.core.bpel/src/main/java/org/opentosca/planbuilder/core/bpel/fragments/BPELProcessFragments.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.core.bpel/src/main/java/org/opentosca/planbuilder/core/bpel/tosca/handlers/NodeRelationInstanceVariablesHandler.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.core.bpel/src/main/java/org/opentosca/planbuilder/core/bpel/tosca/handlers/SimplePlanBuilderServiceInstanceHandler.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.core.bpel/src/main/java/org/opentosca/planbuilder/core/bpel/typebasedplanbuilder/BPELScaleOutProcessBuilder.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.core.bpel/src/main/resources/core-bpel/BpelAssignSelectFromNodeInstancesRequestToStringVar.xml
- pom.xml
Add a missing variable assignment in generated management workflows
* add missing variable assignment
* update winery model version
* cleanup some code style warnings
> Fix generation of management plans

- .github/workflows/dockerhub_stable.yml
Fixes issue with pushing docker images
> fixes issue with pushing only latest tags to docker hub

- org.opentosca.planbuilder/org.opentosca.planbuilder.core.bpel/src/main/java/org/opentosca/planbuilder/core/bpel/typebasedplanbuilder/BPELScaleOutProcessBuilder.java
Adds a check for Tags in the ScaleOutPlanBuilder
> Fix nullpointer in ScaleOutPlanBuilder

- org.opentosca.container.core/src/main/java/org/opentosca/container/core/model/endpoint/AbstractEndpoint.java
fixes issue with long endpoints
> fixes issue with long endpoints

- org.opentosca.container.api/src/main/java/org/opentosca/container/api/controller/CsarController.java
- org.opentosca.container.api/src/main/java/org/opentosca/container/api/service/CsarService.java
- org.opentosca.container.core/src/main/java/org/opentosca/container/core/convention/Utils.java
- org.opentosca.container.core/src/main/java/org/opentosca/container/core/model/ModelUtils.java
- org.opentosca.container.core/src/main/java/org/opentosca/container/core/model/csar/Csar.java
- org.opentosca.container.core/src/main/java/org/opentosca/container/core/model/csar/CsarImpl.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.core.bpel/src/main/java/org/opentosca/planbuilder/core/bpel/artifactbasednodehandler/BPELScopeBuilder.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.core.bpel/src/main/java/org/opentosca/planbuilder/core/bpel/artifactbasednodehandler/DANodeTypeImplCandidate.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.core/src/main/java/org/opentosca/planbuilder/core/plugins/registry/PluginRegistry.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.prephase.plugin.fileupload/src/main/java/org/opentosca/planbuilder/prephase/plugin/fileupload/bpel/BPELPrePhasePlugin.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.prephase.plugin.fileupload/src/main/java/org/opentosca/planbuilder/prephase/plugin/fileupload/bpel/handler/BPELPrePhasePluginHandler.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.provphase.plugin.invoker/src/main/java/org/opentosca/planbuilder/provphase/plugin/invoker/bpel/handlers/BPELInvokerPluginHandler.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.type.plugin.connectsto/src/main/java/org/opentosca/planbuilder/type/plugin/connectsto/bpel/handler/BPELConnectsToPluginHandler.java
If there are multiple DAs that are defined by a parent type, they have not been considerd.
> Fix Uploading DAs

- org.opentosca.planbuilder/org.opentosca.planbuilder.core.bpel/src/main/java/org/opentosca/planbuilder/core/bpel/handlers/BPELFinalizer.java
Something in QHana App doesn't work properly with parallel execution
> turning plans sequential again 

- org.opentosca.planbuilder/org.opentosca.planbuilder.model/src/main/java/org/opentosca/planbuilder/model/plan/AbstractPlan.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.model/src/main/java/org/opentosca/planbuilder/model/plan/bpel/BPELPlan.java
> Moves get tosca ops and iface to abstract plan

- NOTICE
- org.opentosca.planbuilder/org.opentosca.planbuilder.type.plugin.dockercontainer/src/main/java/org/opentosca/planbuilder/type/plugin/dockercontainer/bpel/handler/BPELDockerContainerTypePluginHandler.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.type.plugin.dockercontainer/src/main/java/org/opentosca/planbuilder/type/plugin/dockercontainer/bpel/handler/BPELOpenMTCDockerContainerTypePluginHandler.java
pass PrivilegedMode property of docker container as input to startContainer
see https://github.com/OpenTOSCA/container/issues/257
> add privileged mode to docker container

- org.opentosca.container.api/src/main/java/org/opentosca/container/api/service/PlanService.java
- org.opentosca.container.connector.ode/pom.xml
- org.opentosca.container.connector.ode/src/main/java/org/opentosca/container/connector/ode/OdeConnector.java
- org.opentosca.container.connector.ode/src/main/resources/deploy.wsdl
- org.opentosca.container.connector.ode/src/main/resources/imapi.wsdl
- org.opentosca.container.connector.ode/src/main/resources/pmapi.wsdl
- org.opentosca.container.core/src/main/java/org/opentosca/container/core/next/repository/JpaRepository.java
- org.opentosca.container.engine.plan.plugin.bpel/src/main/java/org/opentosca/container/engine/plan/plugin/bpel/BpelPlanEnginePlugin.java
- org.opentosca.container.war/pom.xml
- org.opentosca.container.war/src/main/resources/logback.xml
- pom.xml
Replaces axis1 client stub generation with axis2
> update ode connector to axis2

- org.opentosca.bus/org.opentosca.bus.management.invocation.plugin.script/src/main/java/org/opentosca/bus/management/invocation/plugin/script/ManagementBusInvocationPluginScript.java
- org.opentosca.container.war/src/test/java/org/opentosca/container/war/tests/ApacheWebAppIntegrationTest.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.type.plugin.patternbased/src/main/java/org/opentosca/planbuilder/type/plugin/patternbased/bpel/PatternBasedHandler.java
> fix for script output parsing

- org.opentosca.container.api/src/main/java/org/opentosca/container/api/controller/BuildPlanController.java
- org.opentosca.container.api/src/main/java/org/opentosca/container/api/controller/ManagementPlanController.java
- org.opentosca.container.core/src/main/java/org/opentosca/container/core/next/repository/PlanInstanceRepository.java
- org.opentosca.container.core/src/main/java/org/opentosca/container/core/next/services/instances/PlanInstanceService.java
Fix issues with lazy loading when retrieving plan instances
> Fix issues with lazy loading when retrieving plan instances

- org.opentosca.container.core/src/main/java/org/opentosca/container/core/next/model/NodeTemplateInstance.java
- org.opentosca.container.core/src/main/java/org/opentosca/container/core/next/model/ServiceTemplateInstance.java
- org.opentosca.container.core/src/main/java/org/opentosca/container/core/next/repository/NodeTemplateInstanceRepository.java
- org.opentosca.container.core/src/main/java/org/opentosca/container/core/next/repository/ServiceTemplateInstanceRepository.java
- org.opentosca.container.core/src/main/java/org/opentosca/container/core/next/services/instances/NodeTemplateInstanceService.java
Some queries to the db didn't return the expected instances i.e. the instances were not properly initialized
> fixes some issue when querying the db via the api

- org.opentosca.container.war/src/test/java/org/opentosca/container/war/tests/QHAnaTest.java
Activate the QHAna test in its latest version and add more complex requests.
> Enable qhana test

- .github/workflows/maven.yml
Adds the functionality to trigger the GitHub workflow with the test cases manually.
See: https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
> Manual test workflow execution
