OpenTOSCA/container

- org.opentosca.container.engine.ia.plugin.tomcat/src/org/opentosca/container/engine/ia/plugin/tomcat/util/messages.properties
- org.opentosca.planbuilder.prephase.plugin.scriptiaonlinux/src/org/opentosca/planbuilder/prephase/plugin/scriptiaonlinux/PrePhasePlugin.java
We are cleaning up the QNames of the types in the OpenTOSCA eco system - see https://github.com/OpenTOSCA/tosca-definitions. The namespace of the WAR type had to be adapted, too. This PR implements that.
> Add support for new QName of WAR artifact type

- org.opentosca.planbuilder.prephase.plugin.scriptiaonlinux/src/org/opentosca/planbuilder/prephase/plugin/scriptiaonlinux/PrePhasePlugin.java
- org.opentosca.planbuilder.type.plugin.dockercontainer/src/org/opentosca/planbuilder/type/plugin/dockercontainer/PluginConstants.java
- org.opentosca.planbuilder.type.plugin.dockercontainer/src/org/opentosca/planbuilder/type/plugin/dockercontainer/handler/Handler.java
These changes should fix spelling of the Docker container artifact and its namespace
* namespace changed from 'opentosca.org/artefacttype' to 'opentosca.org/artifacttype'
* artifact name changed from 'DockerContainerArtefact' to 'DockerContainerArtifact'
* old name and namespace are still supported
> new name and namespace for 'DockerContainerArtifact'

- README.md
Badges are now directly under the header which is their correct position.
> Fix for the badge order in the readme.md

- org.opentosca.bus.management/src/org/opentosca/bus/management/utils/MBUtils.java
This changes fix a nullpointer exception when an IA with no interface is defined in a NodeTypeImplementation for a NodeType, that is a operating system. The current implementation accepts only IAs with defined OperatingSystemInterface but no interface should be accepted too, as it states that all Interfaces of the NodeType are supported by this IA.
> Fix nullpointer when no interface is defined

- org.opentosca.planbuilder.type.plugin.dockercontainer/src/org/opentosca/planbuilder/type/plugin/dockercontainer/bpel/handler/BPELDockerContainerTypePluginHandler.java
- org.opentosca.planbuilder.type.plugin.dockercontainer/src/org/opentosca/planbuilder/type/plugin/dockercontainer/core/DockerContainerTypePluginPluginConstants.java
- enables to set deployment artifacts on docker container node types
- enables to add local file paths stored on the docker engine host that are then added to a started docker container
- enables to to read properties form other templates inside the docker container properties
Basically, enables to model Docker Containers like below. While the attached deployment artifacts are the files to be copied into a volume and attached to the container, ContainerMountPath controls where the volume with the DAs are mounted. HostMountFiles allows to add files to the volume from the Docker Engine Hosts (!) storage, allowing e.g. to add files that are uploaded to the  virtual machine running the docker engine.
Additional small feature for docker containers:
With get_property properties of the docker …
> adds feature that enables to attach files as a docker volume to docker containers

- org.opentosca.planbuilder.type.plugin.dockercontainer/src/org/opentosca/planbuilder/type/plugin/dockercontainer/bpel/handler/BPELDockerContainerTypePluginHandler.java
The DockerContainer NodeType enables to specify environment variables in inheriting NodeTypes, that are passed to the container when it is started.
This PR allows to specify multiple environment variables in one property as well as at any place.
> [Feature] Improve environment variable handling for DockerContainer NodeTypes

- org.opentosca.planbuilder.prephase.plugin.fileupload/src/org/opentosca/planbuilder/prephase/plugin/fileupload/core/PrePhasePlugin.java
Fix, that the planbuilder accepts invalid deployment pairs, e.g. dockerEngine & archives or scripts, as valid pairs.
> [Bug] Fix planbuilder deployment pairs

- org.opentosca.planbuilder.core.bpel/src/org/opentosca/planbuilder/core/bpel/BPELTerminationProcessBuilder.java
- org.opentosca.planbuilder.type.plugin.dockercontainer/src/org/opentosca/planbuilder/type/plugin/dockercontainer/bpel/handler/BPELDockerContainerTypePluginHandler.java
- org.opentosca.planbuilder.type.plugin.dockercontainer/src/org/opentosca/planbuilder/type/plugin/dockercontainer/bpel/handler/BPELOpenMTCDockerContainerTypePluginHandler.java
- org.opentosca.planbuilder.type.plugin.dockercontainer/src/org/opentosca/planbuilder/type/plugin/dockercontainer/core/DockerContainerTypePlugin.java
- org.opentosca.planbuilder.type.plugin.dockercontainer/src/org/opentosca/planbuilder/type/plugin/dockercontainer/core/OpenMTCDockerContainerTypePlugin.java
- org.opentosca.planbuilder.type.plugin.ubuntuvm/src/org/opentosca/planbuilder/type/plugin/ubuntuvm/bpel/BPELUbuntuVmTypePluginHandler.java
somehow the Property name didn't match what the docker container plugin searched  for
DockerContainer NodeType got instead of ContainerImage the ImageID property which enables to set an image Id from dockerhub.
* changes PlanBuilder Plugin for dockercontainers to search for the right property
> fixes issue when starting Containers from ImageID

- org.opentosca.planbuilder.core.bpel/src/org/opentosca/planbuilder/core/bpel/helpers/EmptyPropertyToInputInitializer.java
- org.opentosca.planbuilder.core.bpel/src/org/opentosca/planbuilder/core/bpel/helpers/PropertyMappingsToOutputInitializer.java
- the planbuilders should now only generate inputs needed to comminucate with the ecosystem (servceInstanceID, container API, etc.)
and those specified by get_input in properties
- class that generated output was refactored
Some inputs generated was to prevent issues by issue input for management operations. This is/was legacy behavior to prevent faulty deployment. E.g. DockerEngienCertifcate is an optoinal value, which can, but doesn't have to be set for the deployment of Docker Containers-
* Removes unneccesary input generation, only required meta-data (such as ContainerAPI Url and    ServiceInstanceID) and specified get_input properties are now added to the input of a plan
* Some refactoring for output handling, removes …
> fixes issues with input and outpus of plans

- org.opentosca.planbuilder.core.bpel/src/org/opentosca/planbuilder/core/bpel/BPELBuildProcessBuilder.java
- org.opentosca.planbuilder.core.bpel/src/org/opentosca/planbuilder/core/bpel/BPELScaleOutProcessBuilder.java
- org.opentosca.planbuilder.core.bpel/src/org/opentosca/planbuilder/core/bpel/BPELScopeBuilder.java
- org.opentosca.planbuilder.core.bpel/src/org/opentosca/planbuilder/core/bpel/OperationChain.java
- org.opentosca.planbuilder.core.bpel/src/org/opentosca/planbuilder/core/bpel/PolicyAwareBPELBuildProcessBuilder.java
This resolves the issue of randomly selecting a NodeTypeImplementation, if there are multiple ones for one NodeType.
Now, the first NodeTypeImplementation which implements the required interface(s) is selected.
> Implement Basic NodeTypeImplementation Chooser

- org.opentosca.container.core/src/org/opentosca/container/core/engine/impl/ToscaEngineServiceImpl.java
Because of new features there was a bug in the Tosca Engine returning input parameters instead of output parameters this PR fixes this
> fixes bug in ToscaEngineService which returned input parameters instead of output parameters

- org.opentosca.container.api/src/org/opentosca/container/api/controller/content/DirectoryController.java
Enables to add a ```?recursive``` query param to the content resources, e.g., ```http://localhost:1337/csar/someCsar.csar/content/{optionalDirPath}?recursive```.
This will return all file links relative to the requested directory resource
> adds feature to fetch all content from a csar recursively

- org.opentosca.container.api/src/org/opentosca/container/api/controller/BoundaryDefinitionController.java
- org.opentosca.container.api/src/org/opentosca/container/api/controller/ServiceTemplateInstanceController.java
- org.opentosca.container.api/src/org/opentosca/container/api/dto/boundarydefinitions/PropertiesDTO.java
- org.opentosca.container.api/src/org/opentosca/container/api/dto/boundarydefinitions/PropertyMappingDTO.java
- org.opentosca.container.core/src/org/opentosca/container/core/engine/IToscaReferenceMapper.java
- org.opentosca.container.core/src/org/opentosca/container/core/engine/impl/ToscaReferenceMapper.java
- org.opentosca.container.product/config.ini
Provide access to `BoundaryDefinition` properties and Service Template Instance properties in JSON format via the API, and ensure the TOSCA standard is observed.
* Ensure that the xml fragment returned by `PropertiesDTO` refers only to the section of the properties before `PropertyMappings` (page 85 of [TOSCA 1.0 Standard](http://docs.oasis-open.org/tosca/TOSCA/v1.0/os/TOSCA-v1.0-os.pdf))
* Provide access to Service Template Instance properties in JSON format via the `ServiceTemplateInstanceController` as REST endpoint. This endpoint is meant to be consumed by the [container-client]{https://github.com/OpenTOSCA/container-client}
**Related to**: #
[issue 13](https://github.com/OpenTOSCA/container-client/issues/13)
> Expose service template (instance) properties

- org.opentosca.container.api/src/org/opentosca/container/api/controller/ServiceTemplateInstanceController.java
- org.opentosca.container.api/src/org/opentosca/container/api/controller/SituationsController.java
- org.opentosca.container.api/src/org/opentosca/container/api/service/InstanceService.java
- org.opentosca.container.api/src/org/opentosca/container/api/service/PropertyMappingsHelper.java
- org.opentosca.container.core/src/org/opentosca/container/core/next/model/ServiceTemplateInstance.java
Evaluate `PropertyMappings` when calling the `...instances/{id}/properties` JSON end point with a GET.
* Add an explicit parameter to the `InstanceService.getServiceTemplateInstance` method to indicate whether to evaluate `PropertyMappings` or not
* Add ability to retrieve `ServiceTemplateInstance` properties as a `Document` object.
**Fixes**: #
https://github.com/OpenTOSCA/container-client/issues/13
> Add ability to evaluate property mappings when using the JSON endpoint

- org.opentosca.planbuilder.provphase.plugin.invoker/src/org/opentosca/planbuilder/provphase/plugin/invoker/Activator.java
- org.opentosca.planbuilder.provphase.plugin.invoker/src/org/opentosca/planbuilder/provphase/plugin/invoker/bpel/handlers/ResourceHandler.java
fixes issue with nullpointers when loading an xml fragment and loading of fragments in general in invoker plugin
In a Docker Setup the container couldn't load an xml fragment as the filename was not properly set (although running it in eclipse didn't come up as a nullpointer..)
> fixes issue with nullpointers when loading an xml fragment

- org.opentosca.container.core.impl/src/org/opentosca/container/core/impl/plan/PlanInvocationEngine.java
When invoking a plan via the REST API, non-user-provided parameters should not be expected to be provided by the user!
Before this pull request, these parameters were added by container code BUT with a `null` value. This caused an exception.
* The value of parameters not provided via the API are set to an empty `string` instead of `null`
**Fixes**: https://github.com/OpenTOSCA/container-client/issues/15
> Set the value of empty parameters to empty string

- org.opentosca.container.api/src/org/opentosca/container/api/controller/NodeTemplateInstanceController.java
- org.opentosca.container.api/src/org/opentosca/container/api/controller/RelationshipTemplateInstanceController.java
- org.opentosca.container.api/src/org/opentosca/container/api/dto/request/CreateRelationshipTemplateInstanceRequest.java
- org.opentosca.container.api/src/org/opentosca/container/api/service/InstanceService.java
- org.opentosca.planbuilder.core.bpel/META-INF/resources/schemas/opentoscaapischema.xsd
- org.opentosca.planbuilder.core.bpel/src/org/opentosca/planbuilder/core/bpel/typebasednodehandler/BPELPluginHandler.java
- org.opentosca.planbuilder.core.bpel/src/org/opentosca/planbuilder/core/bpel/typebasedplanbuilder/BPELTerminationProcessBuilder.java
- org.opentosca.planbuilder.postphase.plugin.instancedata/META-INF/resources/BPEL4RESTLightPOST_RelationInstance_InstanceDataAPI.xml
- org.opentosca.planbuilder.postphase.plugin.instancedata/src/org/opentosca/planbuilder/postphase/plugin/instancedata/bpel/Fragments.java
- org.opentosca.planbuilder.postphase.plugin.instancedata/src/org/opentosca/planbuilder/postphase/plugin/instancedata/bpel/Handler.java
Fixes issue with Termination Plan not termination nodes properly when there are multiple nodes
+ added properly instantiating relation instances with the service instance id (fixes #107)
+ fixes termination by looping (again) over the available node instances of service instance
> Fixes issue with Termination Plan

- org.opentosca.planbuilder/src/org/opentosca/planbuilder/AbstractTransformingPlanbuilder.java
+ adds a check that Nodes with State=Running must have no hosting infrastructure defined, hence, it is already running ("as-a-Service")
> fixes issue when nodes have the State=Running property set in the source serviceTemplate of a Transformation Plan

- org.opentosca.bus.management.invocation.plugin.script/src/org/opentosca/bus/management/invocation/plugin/script/ManagementBusInvocationPluginScript.java
- org.opentosca.container.core/src/org/opentosca/container/core/common/Settings.java
- org.opentosca.container.core/src/org/opentosca/container/core/engine/impl/ToscaEngineServiceImpl.java
- org.opentosca.container.product/config.ini
Some IAs are uploaded to certain resources, such as, scripts to VMs. With this feature it can be controlled whether the container should remove or keep those files on the VM, e.g., for debugging purposes
> adds feature to control whether the container deletes IA files

- org.opentosca.planbuilder.type.plugin.connectsto/src/org/opentosca/planbuilder/type/plugin/connectsto/bpel/handler/BPELConnectsToPluginHandler.java
So far, it was not considered whether input parameters of a connectTo operation were required or not. This is fixed with this PR.
> add required input params support

- org.opentosca.container.api/src/org/opentosca/container/api/controller/RootController.java
- org.opentosca.planbuilder.service/META-INF/MANIFEST.MF
- org.opentosca.planbuilder.service/src/org/opentosca/planbuilder/service/resources/RootResource.java
The planbuilder enables to create plans for a given CSAR via a simple API call. It creates a new CSAR with the plans. Feature is used in eclipse winery to pregenerate plans
> fixes issue that caused the planbuilder service not to be available anymore in the API

- org.opentosca.bus.management.service.impl/src/org/opentosca/bus/management/service/impl/ManagementBusServiceImpl.java
- org.opentosca.planbuilder.core.bpel/src/org/opentosca/planbuilder/core/bpel/context/BPELPlanContext.java
- org.opentosca.planbuilder.core.bpel/src/org/opentosca/planbuilder/core/bpel/handlers/BPELFinalizer.java
- org.opentosca.planbuilder.core.bpel/src/org/opentosca/planbuilder/core/bpel/handlers/BPELPlanHandler.java
- org.opentosca.planbuilder.model/src/org/opentosca/planbuilder/model/plan/bpel/BPELScope.java
- org.opentosca.planbuilder.postphase.plugin.instancedata/src/org/opentosca/planbuilder/postphase/plugin/instancedata/bpel/Handler.java
If some errors occur the plans currently call the compensation handlers by adding setting the state to failed within those handlers the instance data can reflect the failing of nodes
> adds feature to set the state of node and relation instances to failed when errors occur

- org.opentosca.planbuilder/org.opentosca.planbuilder.core.bpel/src/main/java/org/opentosca/planbuilder/core/bpel/typebasednodehandler/BPELPluginHandler.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.core.bpel/src/main/java/org/opentosca/planbuilder/core/bpel/typebasedplanbuilder/BPELFreezeProcessBuilder.java
Freeze plan builder didn't work correctly as wrong containerID could be assigned to RemoveContainer Operation.
* Use BPELPluginHandler to handle Termination
> Fix freeze plan builder

- org.opentosca.bus/org.opentosca.bus.management.service/src/main/java/org/opentosca/bus/management/service/impl/ManagementBusServiceImpl.java
- org.opentosca.container.api/src/main/java/org/opentosca/container/api/controller/PlanbuilderController.java
- org.opentosca.container.api/src/main/java/org/opentosca/container/api/controller/RootController.java
- org.opentosca.container.api/src/main/java/org/opentosca/container/api/planbuilder/PlanbuilderWorker.java
- org.opentosca.container.api/src/main/java/org/opentosca/container/api/service/PlanService.java
- org.opentosca.container.control/src/main/java/org/opentosca/container/control/impl/OpenToscaControlServiceImpl.java
- org.opentosca.container.engine.plan.plugin.bpel/src/main/java/org/opentosca/container/engine/plan/plugin/bpel/BpelPlanEnginePlugin.java
- org.opentosca.container.engine.plan/src/main/java/org/opentosca/container/engine/plan/impl/PlanEngineImpl.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.integration/src/main/java/org/opentosca/planbuilder/export/WineryExporter.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.integration/src/main/java/org/opentosca/planbuilder/integration/layer/AbstractImporter.java
- refactors handling of plan ids, it is now more aligned to winery which doesn't care about namespaces
- refactors plan generation to ignore namespaces as winery
- fixes planbuilder service to be able to be used in winery again
- fixes planbuilder to generate plans only when there are none (however is still rather rudimentary)
- fixes invocation of BPMN plans via the management bus
> refactors some aspects of plan management

- org.opentosca.planbuilder/org.opentosca.planbuilder.core.bpel/src/main/java/org/opentosca/planbuilder/core/bpel/tosca/handlers/ServiceTemplateBoundaryPropertyMappingsToOutputHandler.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.integration/src/main/java/org/opentosca/planbuilder/importer/winery/context/impl/impl/PropertyMappingImpl.java
+ fixes OutputHandler to use right imports for NodeTemplate and RelationshipTemplate
+ fixes an issue with finding the right property when IDs used a '.'
> fixes generating plan outputs which use the string concating function

- pom.xml
security fix reported by dependabot
> bump version of google guava to 30.0-jre and higher

- .idea/runConfigurations/Container.xml
- org.opentosca.bus/org.opentosca.bus.management/src/main/java/org/opentosca/bus/management/utils/MBUtils.java
Currently, if a Node Type inherits from another, the Management Bus does not travers the inheritance hierarchy to find interfaces and operations.
* Use the new method that identifies if a specific interface is defined in the hierarchy of a Node Type and returns the corresponding set of management operations.
> Fix Execution of Scripts

- org.opentosca.planbuilder/org.opentosca.planbuilder.type.plugin.dockercontainer/src/main/java/org/opentosca/planbuilder/type/plugin/dockercontainer/bpel/handler/BPELDockerContainerTypePluginHandler.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.type.plugin.dockercontainer/src/main/java/org/opentosca/planbuilder/type/plugin/dockercontainer/core/DockerContainerTypePlugin.java
node templates without a deployment artifact defined throw a nullpointer exception because the model delivers a null instead of an empty list
> fixes a nullpointer when using a docker container 

- org.opentosca.planbuilder/org.opentosca.planbuilder.prephase.plugin.fileupload/src/main/java/org/opentosca/planbuilder/prephase/plugin/fileupload/bpel/BPELPrePhasePlugin.java
Currently, if a new ArtifactType is used as a DA type, then we must always adapt the orchestrator to support this new type. This PR should avoid this for DAs. IAs is a whole different subject...
> Always upload DAs to supported Infra Nodes

- org.opentosca.container.core/src/main/java/org/opentosca/container/core/convention/Interfaces.java
- org.opentosca.container.core/src/main/java/org/opentosca/container/core/convention/Utils.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.core/src/main/java/org/opentosca/planbuilder/core/plugins/utils/PluginUtils.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.type.plugin.ubuntuvm/src/main/java/org/opentosca/planbuilder/type/plugin/ubuntuvm/bpel/BPELUbuntuVmTypePluginHandler.java
The new OpenStack IA requires specific handling of inputs
https://github.com/OpenTOSCA/tosca-definitions-common/pull/21 depends on this.
> Support new OpenStack IA

- org.opentosca.planbuilder/org.opentosca.planbuilder.core.bpel/src/main/java/org/opentosca/planbuilder/core/bpel/typebasedplanbuilder/BPELScaleOutProcessBuilder.java
- org.opentosca.planbuilder/org.opentosca.planbuilder.integration/src/main/java/org/opentosca/planbuilder/integration/layer/AbstractImporter.java
**Fixes**: #294 
However it seems it didn't work only for scale out plans, but thats fixed now. Can't reproduce for other plans.
Tested with the following CSAR: https://drive.google.com/file/d/1V0nwhw_axdsohr83MCnj48JLhfEsYcUe/view?usp=sharing
> fixes issue with generting scaling plans again although they are already available

- org.opentosca.container.api/src/main/java/org/opentosca/container/api/controller/BuildPlanController.java
- org.opentosca.container.core/src/main/java/org/opentosca/container/core/next/xml/PropertyParser.java
If there are no Properties defined on a NodeTemplate (and literally no Properties element inside a TOSCA document) the parsing of properties fail
> fixes an error when there are no properties defined in a NodeTemplate

- .github/workflows/dockerhub.yml
- .github/workflows/dockerhub_stable.yml
- .github/workflows/image.yml
- .github/workflows/image_stable.yml
- .github/workflows/maven.yml
This PR
- replaces Docker Hub with the GitHub registry in the GitHub workflow and updates the used GitHub actions
- temporarily disables the PlanQK Service integration test as it's not compatible anymore with the platforms' authentication
Needed for https://github.com/OpenTOSCA/opentosca-docker/pull/57
> GitHub registry
